%YAML 1.2
---
# Default parameters for the Tracking program
# All parameters can be changed to accommodate user needs.
# All parameters can be changed at runtime with the appropriate config window
User:
  name: Aquiles

Saving:
  auto_save: False
  auto_save_waterfall: True
  directory: C:\data\nanoCET
  filename_video: Video # Can be the same filename for video and photo
  filename_photo: Snap
  filename_waterfall: Waterfall
  filename_trajectory: Trajectory
  filename_log: Log
  max_memory: 800 # In megabytes

GUI:
  length_waterfall: 20 # Total length of the Waterfall (lines)
  refresh_time: 100 # Refresh rate of the GUI (in ms)

Camera:
  model: hamamatsu # Should be a python file in model/cameras
  init: 0 # Initial arguments to pass when creating the camera
  #extra_args: [extra, arguments] # Extra arguments that can be passed when constructing the model
  model_camera: Orca Flash # To keep a registry of which camera was used in the experiment
  exposure_time: 200 # Initial exposure time (in ms)
  binning_x: 1 # Binning
  binning_y: 1
  roi_x1: 0 # Leave at 0 for full camera
  roi_x2: 0
  roi_y1: 0
  roi_y2: 0
  background: '' # Full path to background file, or empty for none.
  background_method: [Method1, Method2]


Tracking: # Not yet implemented, will show up in the config window
  param_1: 0.
  param_2: 0

Debug:
  queue_memory: False
  to_screen: True
